FROM docker.io/library/busybox:uclibc
LABEL maintainer="Podman Maintainers"
LABEL artist="Máirín Ní Ḋuḃṫaiġ, Twitter:@mairin"
LABEL io.containers.capabilities="sys_chroot"
COPY podman_hello_world.sh /usr/local/bin/podman_hello_world
CMD ["/usr/local/bin/podman_hello_world"]
